### PR TITLE
[Fixes #85] Adding logs parameter for stop-containers

### LINKED ISSUE #85: Provide option to save container logs when stop-containers runs
Especially when docker containers are cleaned up after a build, it would be useful to have the option to save the logs to files under target. PR to follow.

### PR DESCRIPTION
**Pull request by jdcasey**
Allows build to save container logs to the specified directory, with the filename format <container-name>.log. Disabled by default (empty `logs` parameter).

### CODE REVIEW

**Comment by wouterd** [comment]
Thanks for the PR! Did some slight changes to make the code a bit more in line with the rest of the code base.

**Comment by jdcasey** [comment]
Cool. Not to pressure you, but do you plan to release anytime soon?

**Comment by wouterd** [comment]
I just pushed v4.1.0 of the plugin to maven central, should be there within a few hours.

**Comment by jdcasey** [comment]
Thanks!

**Pull request merged**
